#!/bin/bash

function usage {
  cat<<EOF
Usage: ./install <install-to-path>
  See INSTALL.md for instructions.
EOF
}

function failure_and_die {
  echo "UPC++ Installation failed. Please report the entire log above to: upcxx@googlegroups.com" >&2
  exit 1
}

if [[ "$1" = "-h" || "$1" = "--help" ]]; then
  usage
  exit 0
elif [ "$#" -eq 1 ]; then
  single=0
  install_to="$1"
elif [ "$#" -eq 2 ]; then
  if [ "$1" != "--single" ]; then
    >&2 usage
    exit 1
  fi
  single=1
  install_to="$2"
else
  >&2 usage
  exit 1
fi

# Configure
config_cmd="./configure --prefix='${install_to}'"
[[ "$single" -eq 1 ]] && config_cmd+=' --single'
eval $config_cmd

# TODO: autoconf or cmake can/should enforce GNU make
GMAKE=${UPCXX_MAKE:-make -j8}

if [ "$single" -eq 1 ]; then
  eval $($GMAKE --no-print-directory echovar VARNAME=GASNET)
  [ -r "$GASNET/gasnet_config.h" ] && target=install-single-bld || target=install-single-src
  eval $GMAKE $target
  if [ $? -ne 0 ]; then failure_and_die; fi
else
  eval $GMAKE install
  if [ $? -ne 0 ]; then failure_and_die; fi
fi

echo "UPC++ successfully installed"
