#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo 'Usage: install <directory-path>' >&2
  exit 1
fi

. sourceme
INSTALL_DIR=$(absify "$1")

. utils/system-checks.sh
sys_info
platform_sanity_checks

nobs install src/upcxx.cpp $INSTALL_DIR || \
  ( echo "UPC++ Installation failed. Please report the entire log above to: upcxx@googlegroups.com" ; exit 1; )

echo "UPC++ successfully installed"
