#!/bin/bash

export GASNET_BACKTRACE=1

. sourceme
rm -rf .nobs

. utils/system-checks.sh
sys_info

echo "Checking platform..."
platform_sanity_checks

cd test

echo "Setting up upcxx..."
nobs run hello_upcxx.cpp &> .run-tests.err
if [ $? -ne 0 ]; then
		echo "Set up failed, here is the trace:"
		cat .run-tests.err
		exit 0
fi
rm .run-tests.err

run_test() {
		echo "Running test $1"
		nobs run $1 > .run-tests.out 2> .run-tests.err
		err=$?
		grep "Test result: " .run-tests.out
		if [ $err -ne 0 ]; then
				echo -e "\e[91mTest failed, here is the trace:\e[0m"
				cat .run-tests.err
				rm .run-tests.err
				exit $err
		fi
		rm .run-tests.err
}

# Run on all available cores by default - this works on Mac and Linux
export GASNET_PSHM_NODES=${RANKS:=`getconf _NPROCESSORS_ONLN`}

echo "Running tests on $RANKS ranks..."

run_test "atomics.cpp"
run_test "collectives.cpp"
run_test "dist_object.cpp"
run_test "future.cpp"
run_test "rpc_barrier.cpp"
run_test "rpc_ff_ring.cpp"
run_test "rput.cpp"
run_test "uts/uts_ranks.cpp"
run_test "uts/uts_threads.cpp"
UPCXX_BACKEND=gasnetex_par run_test "uts/uts_hybrid.cpp"

echo -e "\e[92mAll tests succeded\e[0m"

cd ..
