#!/bin/bash

if [ "$1" == "-h" ]; then
    echo "Usage: RANKS=<ranks> CONDUIT=<smp|udp> ./run-tests"
    echo "  Defaults to the number of available hardware threads for RANKS, and the udp CONDUIT"
    exit 0
fi
    
. sourceme
rm -rf .nobs

. utils/system-checks.sh
sys_info

echo "Checking platform..."
platform_sanity_checks

# Check for supported conduits
if [ -z "$CONDUIT" ]; then
    export CONDUIT=udp
elif [ "$CONDUIT" != "udp" ] && [ "$CONDUIT" != "smp" ]; then
    echo "At this point, only the udp and smp conduits are supported"
    echo "Set CONDUIT=smp or CONDUIT=udp"
    exit 0
fi
echo "Using $CONDUIT conduit (set environment variable CONDUIT=<smp|udp> to change)"

# Run on all available cores by default - this works on Mac and Linux
if [ -z "$RANKS" ]; then
    export RANKS=`getconf _NPROCESSORS_ONLN`
    echo "Detected $RANKS hardware threads (set environment variable RANKS=<ranks> to change)"
fi
echo "Running tests on $RANKS ranks"

check_result() {
    if [ $1 -ne 0 ]; then
        echo -e "\e[91m$2 failed, the trace can be found in test/run-tests.err\e[0m"
        # force a flush
        cat .run-tests.err > run-tests.err
        rm .run-tests.err
        rm -rf .nobs
        exit 1
    fi
}

export GASNET_CONDUIT=$CONDUIT
export GASNET_BACKTRACE=1
# default to debugging mode
export DBGSYM=${DBGSYM:=1}
export OPTLEV=${OPTLEV:=0}

cd test

echo "Setting up upcxx... (this may take a while)"
nobs exe hello_upcxx.cpp &> .run-tests.err
check_result $? "Setup"
rm .run-tests.err

run_test() {
    echo "Running test $1"
    nobs run "$1" &> .run-tests.err
    check_result $? "Test"
    grep "Test result: " .run-tests.err
    rm .run-tests.err
}


run_test "atomics.cpp"
run_test "collectives.cpp"
run_test "dist_object.cpp"
run_test "future.cpp"
run_test "lpc_barrier.cpp"
run_test "rpc_barrier.cpp"
run_test "rpc_ff_ring.cpp"
run_test "rput.cpp" "par"
run_test "uts/uts_ranks.cpp"
THREADS="$RANKS" run_test "uts/uts_threads.cpp"

UPCXX_BACKEND=gasnetex_par run_test "uts/uts_hybrid.cpp"

echo -e "\e[92mAll tests succeded\e[0m"

cd ..

rm -rf .nobs 2>&1 >/dev/null # ignore failures due to races

exit 0
