#!/bin/bash

## BOILERPLATE
source $(dirname $0)/_ci-common

## ENVIRONMENT
module purge
module load openmpi
module load cmake
export TMPDIR=$XDG_RUNTIME_DIR
export GASNET_SPAWNFN=L
export GASNET_SUPERNODE_MAXSIZE=2
export UPCXX_HAVE_OPENMP=1

export NETWORKS="${CI_NETWORKS:-ibv}"
export GMAKE="${CI_MAKE:-${GMAKE:-make}}"
MAKE_CMD="$GMAKE ${CI_MAKE_PARALLEL:--j32}"

GCC_PREFIX="${GCC_PREFIX:-~phargrov/pkg/gcc-aarch64/10.2.0}"
eval GCC=${GCC_PREFIX}/bin/gcc
eval GXX=${GCC_PREFIX}/bin/g++

## CONFIGURE
if [[ $STAGES =~ ,configure, ]]; then
  $UPCXX/configure ${GASNET:+ --with-gasnet=$GASNET} CC=$GCC CXX=$GXX \
        --without-mpicc --with-ibv-physmem-max=2/3 --enable-ibv-multirail
fi

## BUILD
if [[ $STAGES =~ ,build, ]]; then
  time $MAKE_CMD all
fi

## TESTS
if [[ $STAGES =~ ,tests, ]]; then
  time $MAKE_CMD dev-tests
fi

## RUN
unset TMPDIR
if [[ $STAGES =~ ,run, ]]; then
  time salloc -t 90 -N 2 -- $GMAKE dev-run-tests
fi

## DONE
success
